import type { Metadata } from 'next';
import '@mantine/core/styles.css';
import {
  ColorSchemeScript,
  createTheme,
  MantineProvider,
  DirectionProvider,
  mantineHtmlProps,
} from '@mantine/core';
import '@/assets/main.css';
import classes from './style.module.scss';
import './font.module.scss';
import Providers from '@/services/provider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const theme = createTheme({
  fontFamily: 'vazir',
  fontFamilyMonospace: 'vazir',
  headings: { fontFamily: 'vazir' },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DirectionProvider initialDirection='rtl'>
      <html lang='fa' dir='rtl' {...mantineHtmlProps}>
        <head>
          <ColorSchemeScript />
        </head>
        <body className={classes['body']}>
          <ToastContainer />
          <Providers>
            <MantineProvider theme={theme}>
              <div className={classes['wrapper']}>
                <div className={classes['app']}>{children}</div>
              </div>
            </MantineProvider>
          </Providers>
        </body>
      </html>
    </DirectionProvider>
  );
}
